export const GET_DATA = 'GET_DATA';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VALIDATE_CODE = 'VALIDATE_CODE';
export const STORE_INFO = 'STORE_INFO';
export const GET_ALL_PASSIONS = 'GET_ALL_PASSIONS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const DUMMY_USER_SUCCESS = 'DUMMY_USER_SUCCESS';
export const DUMMY_USER_FAILURE = 'DUMMY_USER_FAILURE';

export const PUBLISH_CONTRIBUTION = 'PUBLISH_CONTRIBUTION';
export const PUBLISH_WORK = 'PUBLISH_WORK';
export const GET_ALL_USER_WORKS = 'GET_ALL_USER_WORKS';
export const GET_ALL_USER_CONTRIBUTIONS = 'GET_ALL_USER_CONTRIBUTIONS';
export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';